name: 'Build Flatpak'
description: 'Build and upload a Flatpak'
inputs:
  arch:
    description: 'Architecture to build Flatpak for'
    required: true
  bundle-name:
    description: 'Name of the Flatpak bundle to output'
    required: true
  manifest:
    description: 'Path to the Flatpak manifest to build'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    # Docker is required by the docker/setup-qemu-action which enables emulation
    - name: Install Docker dependency
      shell: bash
      run: |
        dnf -y install docker
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: ${{ inputs.bundle-name }}
        manifest-path: ${{ inputs.manifest }}
        arch: ${{ inputs.arch }}
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.arch }}-${{ inputs.bundle-name }}
        path: ${{ inputs.bundle-name }}
    - uses: actions/upload-artifact@v3
      with:
        name: repo-${{ inputs.arch }}-${{ inputs.bundle-name }}
        path: repo/
    - uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v4
      if: github.event_name != 'pull_request'
      name: "Deploy"
      with:
        repository: ${{ inputs.repository }}
        flat-manager-url: https://flatpak.vicr123.com
        token: ${{ inputs.repo-token }}