name: 'Build Flatpak'
description: 'Build and upload a Flatpak'
inputs:
  arch:
    description: 'Architecture to build Flatpak for'
    required: true
  repo-token:
    description: 'Token to authenticate to Flatpak server with'
    required: true
  repository:
    description: 'Flatpak repository to deploy to'
    required: true
  bundle-name:
    description: 'Name of the Flatpak bundle to output'
    required: true
  manifest:
    description: 'Path to the Flatpak manifest to build'
    required: true
  deploy:
    description: 'Whether to deploy the Flatpak'
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - uses: vicr123/libcontemporary/cpp-problem-matcher@actions
      name: "Install C++ problem matcher"
    - uses: actions/checkout@v2
    # Docker is required by the docker/setup-qemu-action which enables emulation
    - name: Install Docker dependency
      shell: bash
      run: |
        dnf -y install docker
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: ${{ inputs.bundle-name }}
        manifest-path: ${{ inputs.manifest }}
        cache-key: flatpak-builder-${{ inputs.manifest }}
        arch: ${{ inputs.arch }}
    - uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v6.1
      if: github.event_name != 'pull_request' && inputs.deploy == true
      name: "Deploy"
      with:
        repository: ${{ inputs.repository }}
        flat-manager-url: https://flatpak.vicr123.com
        token: ${{ inputs.repo-token }}
