name: 'Build Flatpak'
description: 'Build and upload a Flatpak'
inputs:
  arch:
    description: 'Architecture to build Flatpak for'
    required: true
  repo-token:
    description: 'Token to authenticate to Flatpak server with'
    required: true
  repository:
    description: 'Flatpak repository to deploy to'
    required: true
  bundle-name:
    description: 'Name of the Flatpak bundle to output'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    # Docker is required by the docker/setup-qemu-action which enables emulation
    - name: Install Docker dependency
      shell: bash
      run: |
        dnf -y install docker
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64
    - uses: actions/download-artifact@v3
      with:
        name: repo-${{ inputs.arch }}-${{ inputs.bundle-name }}
    - uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v4
      if: github.event_name != 'pull_request'
      name: "Deploy"
      with:
        repository: ${{ inputs.repository }}
        flat-manager-url: https://flatpak.vicr123.com
        token: ${{ inputs.repo-token }}