version: 1.0.{build}
branches:
  only:
  - blueprint
skip_tags: true
image: Visual Studio 2019

environment:
  REPO_SLUG: vicr123/the-libs
  deploy_project: the-libs
  deploy_version: ''
  deploy_artifact: ''
    
build_script:
- cmd: >-
    appveyor\build.bat

test: off
