name: 'Build Project'
description: 'Build and install a libcontemporary project'
inputs:
  project:
    description: 'Project slug to build or "." to build current project'
    required: true
  commitish:
    description: 'Tag/branch/etc. to build'
    required: false
  extra-cmake-args:
    description: 'Extra CMake args for project'
    required: false
    default: ''
  arch:
    description: 'Architecture of build'
    required: false
    default: 'x64'
  force-host-build:
    description: 'Build project for the host system regardless of LCNTP_TARGET_PLATFORM environment variable'
    required: false
    default: 'false'
  target:
    description: 'Target to build'
    required: false
    default: ''
outputs:
  install-prefix:
    description: "Path to installed files"
runs:
  using: 'node16'
  main: 'dist/index.js'
