name: 'Build Project'
description: 'Build and install a libcontemporary project'
inputs:
  project:
    description: 'Project slug to build or "." to build current project'
    required: true
  commitish:
    description: 'Tag/branch/etc. to build'
    required: false
  extra-cmake-args:
    description: 'Extra CMake args for project'
    required: false
    default: ''
  arch:
    description: 'Architecture of build'
    required: false
    default: 'x64'
runs:
  using: 'node16'
  main: 'dist/index.js'
