name: 'Install libcontemporary'
description: 'Install libcontemporary'
inputs:
  commitish:
    description: 'Branch to build'
    default: "blueprint"
    required: false
runs:
  using: 'composite'
  steps:
    - uses: vicr123/libcontemporary/build-project@actions
      name: "Build QCoro"
      with:
        project: "danvratil/qcoro"
        commitish: "v0.7.0"
    - uses: vicr123/libcontemporary/build-project@actions
      name: "Build libcontemporary"
      with:
        project: "vicr123/libcontemporary"
        commitish: ${{ inputs.commitish }}
