name: "Windows CI"
on:
  push:
    branches:
      - "master"
      - "blueprint"
      - "features/*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        qt: [6.3, 6.4.2, 6.5]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: vicr123/libcontemporary/prepare-vars@actions
        id: vars
        with:
          qtVersion: ${{ matrix.qt }}
      - name: Install ninja
        run: |
          choco install ninja
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ steps.vars.outputs.qtVersion }}
          arch: win64_msvc2019_64
          modules: addons.qtmultimedia addons.qtwebsockets qt5compat
          cache: true
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1.12.0
        with:
          sdk: 10.0.22000.0
      - uses: vicr123/libcontemporary/build-project@actions
        name: "Build QCoro"
        with:
          project: "danvratil/qcoro"
          commitish: ${{ steps.vars.outputs.qcoroVersion }}
      - uses: actions/checkout@v1
        with:
          submodules: 'recursive'
      - uses: vicr123/libcontemporary/build-project@actions
        name: "Build project"
        with:
          project: "."
